version: '3.9'

services:
  next:
    build: .
    command: sh -c "yarn build && yarn start"
    volumes:
      - next-build:/home/next/build
  nginx:
    depends_on:
      - next
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    image: nginx:stable-alpine
    entrypoint: nginx -g 'daemon off;'
    ports:
      - 3000:80

volumes:
  next-build:
