name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ github.run_id }}
      - name: Install dependencies
        run: yarn install --immutable

  lint:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ github.run_id }}
      - run: yarn tsc
      - run: yarn eslint
      - run: yarn stylelint

  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ github.run_id }}
      - run: yarn build
