name: restarter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: yarn set version berry
      - run: yarn install --immutable
      - run: yarn tsc
      - run: yarn eslint
      - run: yarn stylelint
      - run: yarn build
